import { filterPosts } from "@/utils/filterPosts"
import { Post } from "@/utils/type"

export const fetchSearchResultsAPI = async (samplePosts: Post[], searchKeyword: string): Promise<Post[]> => {
    return filterPosts(samplePosts, searchKeyword)
}

export const samplePosts: Post[] = [
    {
        postId: 1,
        userProfile: "",
        thumbnail: "",
        title: "룰루랄라 프랑스 여행 중",
        continent: "유럽",
        country: "프랑스",
        nickName: "Amy",
        createdAt: new Date("2022-06-01T12:00:00"),
        commentCount: 10,
        likeCount: 20,
        content: "모비",
    },
    {
        postId: 2,
        userProfile: "",
        thumbnail: "",
        title: "나는 국내가 좋아",
        continent: "아시아",
        country: "한국",
        nickName: "Gang",
        createdAt: new Date("2022-06-05T15:30:00"),
        commentCount: 5,
        likeCount: 15,
        content: "모비",
    },
    {
        postId: 3,
        userProfile: "",
        thumbnail: "",
        title: "일본 갔다 왔어요!",
        continent: "아시아",
        country: "일본",
        nickName: "Kimi",
        createdAt: new Date("2022-06-05T15:30:00"),
        commentCount: 5,
        likeCount: 15,
        content: "모비",
    },
    {
        postId: 4,
        userProfile: "",
        thumbnail: "",
        title: "미국 여행 중",
        continent: "북아메리카",
        country: "미국",
        nickName: "Wendy",
        createdAt: new Date("2022-06-05T15:30:00"),
        commentCount: 5,
        likeCount: 15,
        content: "모비",
    },
    {
        postId: 5,
        userProfile: "",
        thumbnail: "",
        title: "겨울에 너무 추워",
        continent: "유럽",
        country: "노르웨이",
        nickName: "Jayden",
        createdAt: new Date("2022-06-01T12:00:00"),
        commentCount: 10,
        likeCount: 20,
        content: "모비",
    },
    {
        postId: 6,
        userProfile: "",
        thumbnail: "",
        title: "우유니 사막 최고",
        continent: "남아메리카",
        country: "볼리비아",
        nickName: "Louis",
        createdAt: new Date("2022-06-05T15:30:00"),
        commentCount: 5,
        likeCount: 43,
        content: "모비",
    },
    {
        postId: 7,
        userProfile: "",
        thumbnail: "",
        title: "휴양은 바다지",
        continent: "아시아",
        country: "코타키나발루",
        nickName: "DK",
        createdAt: new Date("2022-06-05T15:30:00"),
        commentCount: 20,
        likeCount: 9,
        content: "모비",
    },
    {
        postId: 8,
        userProfile: "",
        thumbnail: "",
        title: "특이한 곳 여행이 취미",
        continent: "아프리카",
        country: "이집트",
        nickName: "Jun",
        createdAt: new Date("2022-06-05T15:30:00"),
        commentCount: 30,
        likeCount: 15,
        content: "모비",
    },
]
