#!/usr/bin/env sh

# 브랜치 이름에서 티켓 번호 추출을 위한 정규식
# 브랜치 이름이 "YG-9-setting"과 같은 형식일 경우 추출
# 브랜치 이름에서 "YG-"로 시작하는 부분을 추출하여 티켓 번호로 사용
BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
if [[ $BRANCH_NAME =~ YG-([0-9]+)- ]]; then
    TICKET_ID=${BASH_REMATCH[1]}
    echo "JIRA 티켓 번호: $TICKET_ID"
    # 여기서 JIRA 티켓 번호를 활용하여 원하는 작업을 수행할 수 있습니다.
else
    echo "JIRA 티켓 번호를 추출할 수 없는 브랜치입니다."
fi
